<?php

namespace Modules\Everymarket\Console;

use App\Conversation;
use App\Thread;
use Illuminate\Console\Command;

/**
 * Delete threads which are re-imported copies of FreeScout's own outgoing
 * emails (Auto-BCC / routing rules delivered them back to the INBOX and the
 * fetcher saved them as new threads).
 *
 * A copy is identified by its stored message_id matching the pattern
 * FS_reply-{thread_id}-{hash}@... where the hash is verified against
 * MailHelper::getMessageIdHash() and the original thread exists.
 * The fetch_emails.should_save_thread hook in the module provider prevents
 * new ones from being created.
 */
class CleanupDuplicateThreads extends Command
{
    protected $signature = 'everymarket:cleanup-duplicate-threads
        {--mailbox= : Limit to conversations of this mailbox ID}
        {--limit=0 : Process at most N duplicates (0 = all)}
        {--dry-run : Show what would be deleted without deleting}';

    protected $description = 'Delete threads which are re-imported copies of own outgoing emails';

    public function handle()
    {
        $prefixes = [
            \MailHelper::MESSAGE_ID_PREFIX_REPLY_TO_CUSTOMER,
            \MailHelper::MESSAGE_ID_PREFIX_AUTO_REPLY,
        ];

        $query = Thread::where(function ($query) use ($prefixes) {
            foreach ($prefixes as $prefix) {
                $query->orWhere('threads.message_id', 'like', $prefix.'-%');
            }
        });

        if ($this->option('mailbox')) {
            $query->join('conversations', 'conversations.id', '=', 'threads.conversation_id')
                ->where('conversations.mailbox_id', (int) $this->option('mailbox'))
                ->select('threads.*');
        }

        $candidates = $query->orderBy('threads.id')->get();
        $this->line(count($candidates).' candidate thread(s) found by Message-ID pattern.');

        $limit = (int) $this->option('limit');
        $deleted = 0;
        $skipped = 0;
        // Conversations to update counters for: id => conversation.
        $touched_conversations = [];

        foreach ($candidates as $thread) {
            if ($limit && $deleted >= $limit) {
                break;
            }

            // Verify this is really an ID generated by this instance
            // for an existing thread.
            $original = null;
            foreach ($prefixes as $prefix) {
                if (preg_match('/^'.preg_quote($prefix, '/').'\-(\d+)\-([a-z0-9]+)@/', $thread->message_id, $m)
                    && $m[2] == \MailHelper::getMessageIdHash($m[1])
                ) {
                    $original = Thread::find($m[1]);
                    break;
                }
            }

            if (!$original || $original->id == $thread->id) {
                $this->line('Thread #'.$thread->id.': hash mismatch or original thread missing - skipping.');
                $skipped++;
                continue;
            }

            $this->info('Thread #'.$thread->id.' (conversation #'.$thread->conversation_id.'): duplicate of outgoing thread #'
                .$original->id.' (conversation #'.$original->conversation_id.')');

            if ($this->option('dry-run')) {
                $deleted++;
                continue;
            }

            // Backup before deleting.
            $backup_dir = storage_path('app/em-thread-cleanup');
            if (!is_dir($backup_dir)) {
                mkdir($backup_dir, 0755, true);
            }
            file_put_contents(
                $backup_dir.'/thread_'.$thread->id.'.json',
                json_encode($thread->getAttributes(), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
            );

            $conversation = $thread->conversation;
            // Deletes attachments and the thread itself.
            $thread->deleteThread();

            if ($conversation) {
                $touched_conversations[$conversation->id] = $conversation;
            }

            $deleted++;
        }

        // Recalculate counters and preview once per affected conversation.
        if (!$this->option('dry-run')) {
            foreach ($touched_conversations as $conversation) {
                $conversation->threads_count = $conversation->threads()
                    ->whereIn('type', [Thread::TYPE_CUSTOMER, Thread::TYPE_MESSAGE])
                    ->where('state', Thread::STATE_PUBLISHED)
                    ->count();

                $last = $conversation->threads()
                    ->whereIn('type', [Thread::TYPE_CUSTOMER, Thread::TYPE_MESSAGE])
                    ->where('state', Thread::STATE_PUBLISHED)
                    ->orderByDesc('created_at')
                    ->first();
                if ($last) {
                    $conversation->last_reply_at = $last->created_at;
                    $conversation->last_reply_from = ($last->type == Thread::TYPE_CUSTOMER)
                        ? Conversation::PERSON_CUSTOMER
                        : Conversation::PERSON_USER;
                }

                $conversation->save();

                Conversation::updatePreview($conversation->id);
            }
        }

        $this->info('Deleted: '.$deleted.', skipped: '.$skipped
            .($this->option('dry-run')
                ? ' (dry run - nothing deleted)'
                : '. Backups in storage/app/em-thread-cleanup/, '.count($touched_conversations).' conversation(s) counters updated.'));

        return 0;
    }
}
